### ISSUE TITLE
folder picker instead of file picker

### ISSUE THREAD

**Issue by jasedwards** [mgechev/ngrev#10]
Apologies if I am doing something dumb.  I just installed latest windows version.  when I click select project a folder picker comes up instead of file picker so that I am not actually able to select a tsconfig file.  I am on Windows 7

**Comment by mgechev** [comment]
Yes, it's ok. ngast will automatically discover the `tsconfig.json` file. Do you experience issues in your project being rendered?

**Comment by jasedwards** [comment]
yeah, it immediately has (Not Responding) along the top and I have to end process.

**Comment by mgechev** [comment]
It should be: `[YOUR_CLI_APP]/src/tsconfig.app.json`

**Comment by jasedwards** [comment]
ah.  duh.  I even read that twice on the read me file.  that got it working.  Thanks.

**Comment by mgechev** [comment]
No worries. I'll change it to file picker in 10 mins.

**Comment by mgechev** [comment]
https://github.com/mgechev/ngrev/commit/4ee2d2349e9116714f5f81d74b0bb7c1cd5227c2

**Comment by mgechev** [comment]
https://github.com/mgechev/ngrev/releases/tag/0.0.4
