### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by mgechev** [mgechev/ngrev#101]
The app binaries produced by `yarn electron:build` do not work.

**Comment by vik-13** [comment]
Here is the quick fix:
https://github.com/mgechev/ngrev/pull/102

It's not optimal build process. I think would be great to have shared dest folder for both build processes. Currently electron app is compiled into src and both angular app and electron app duplicates assets.

**Comment by vik-13** [comment]
There is another issue:
/release/angular-electron.dmg - It cannot load the project..just loader animation is shown all the time.
/release/mac/angular-electron works fine for me.

I suppose some options are missed..

**Comment by vik-13** [comment]
Looks like if you open the app outside the release/mac folder the child_process cannot resolve dependencies correctly..

**Comment by mgechev** [comment]
>It's not optimal build process. I think would be great to have shared dest folder for both build processes. Currently electron app is compiled into src and both angular app and electron app duplicates assets.

I agree.

**Comment by mgechev** [comment]
Ideally we don't want to disable asar, but this seems to be the only option. I don't think it'll impact the performance significantly for such a small app.

**Comment by vik-13** [comment]
> Ideally we don't want to disable asar, but this seems to be the only option. I don't think it'll impact the performance significantly for such a small app.

Yes, I also haven't found another solution...
