### ISSUE TITLE
Subset of modules appearing in the visulisation

### ISSUE THREAD

**Issue by kyranjamie** [mgechev/ngrev#11]
### Issue

Only 3 module boxes are rendering, where app has many more modules than this.  Haven't had time to investigate further, but will drop here in case it helps.

![image](https://cloud.githubusercontent.com/assets/1618764/25326076/c6910bf8-28ce-11e7-9f14-ed01bb744c9c.png)

Folder structure is as follows. `yy` and `xx` are licensees of a white labelable app, all implementing base modules of `core`

```
src
├── core
│   ├── +cms
│   ├── +crm
│   ├── +logs
│   ├── +reports
│   ├── +settlements
│   ├── actions
│   ├── app-routing.module.ts
│   ├── app.module.ts
│   ├── components
│   ├── containers
│   ├── core.scss
│   ├── domain.enum.ts
│   ├── effects
│   ├── guards
│   ├── models
│   ├── reducers
│   ├── services
│   ├── shared
│   ├── testing
│   └── utils
├── yy
│   ├── +cms
│   ├── +crm
│   ├── +logs
│   ├── +reports
│   ├── +settlements
│   ├── _config.js
│   ├── yy-routing.module.ts
│   ├── yy.module.hot.ts
│   └── yy.module.ts
├── xx
│   ├── ...
├── main-yy.aot.ts
├── main-yy.ts
├── main-xx.aot.ts
├── main-xx.ts
├── polyfills.ts
└── vendor.ts
```

App is AoT compliant and compiles with the latest version of ngc.

**Comment by mgechev** [comment]
This is most likely caused by ngast. I'll take a look at the issue, thanks!

**Comment by mgechev** [comment]
@kyranjamie would you share your tsconfig.json? Also, do you have any of these modules being loaded lazily?

**Comment by kyranjamie** [comment]
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@core/*": ["core/*"],
      "@ui/*": ["ui/*"]
    },
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./dist/out-tsc",
    "sourceMap": false,
    "target": "es5",
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "./src/ngfactory"
  }
}
```

**Comment by mgechev** [comment]
@kyranjamie is it a CLI project? Probably you have lazy loaded modules (`loadChildren`)?

**Comment by mgechev** [comment]
@kyranjamie reproduced the issue. Most likely your project is compliant with ngc but you still may get warnings for non-exported symbols, for instance. It'll be a good idea ngrev to show such warnings.

I'll output notification by the end of the day.

**Comment by mgechev** [comment]
Try the current code in master (`npm run build && npm start`). It'll output the error message gotten from the compiler.

**Comment by kyranjamie** [comment]
No, error from compiler.  The project is using `loadChildren`, but still there is a top level non-lazyloaded AppComponent not displayed.  Who knows 🤷‍♂️

**Comment by mgechev** [comment]
I'll keep it open. If you can create a minimum demo which will allow me to reproduce the problem it'll be great.

In case anyone is able to reproduce, please comment.

**Comment by mgechev** [comment]
@kyranjamie FYI, there's support for lazy-loaded modules now https://github.com/mgechev/ngrev/commit/5f5f88c04c3236807e4f4c4b6fcb397e7d98fe5c. It's not released yet, so you can only try it with:

```
$ git clone https://github.com/mgechev/ngrev
$ cd ngrev && yarn install && npm run build && npm start
```
