### ISSUE TITLE
Lazy loaded modules

### ISSUE THREAD

**Issue by mgechev** [mgechev/ngrev#12]
The lazy loaded modules should be shown on module level and connected to their parent with a dashed arrow.

**Comment by MrCroft** [comment]
Not when they're nested.
For example, I have AppModule that includes a DashboardModule.
The DashboardModule, in it's turn, lazy loads a bunch of other modules. And those lazily loaded modules don't show up anywhere in ngrev.

You can notice that with the client app I have here: [https://github.com/MrCroft/ngx-uploader-demo/tree/master/client](https://github.com/MrCroft/ngx-uploader-demo/tree/master/client)

**Comment by mgechev** [comment]
@MrCroft just noticed that there's some regression. Thanks for reporting this.

**Comment by mgechev** [comment]
The problems are summarized by these issues. Will push a fix in a minute https://github.com/mgechev/ngrev/issues/15 https://github.com/mgechev/ngrev/issues/16.

**Comment by mgechev** [comment]
In a bit you can download 0.0.9 and try it out.

**Comment by MrCroft** [comment]
So fast! Thank you. I've just discovered ngrev. I've fallen a bit behind in the Angular world in the last 2 months.

**Comment by MrCroft** [comment]
It still behaves a bit weird for my app.
It only shows me 3 modules once I double click `DashboardModule`, but none of the lazily loaded ones.
![image](https://cloud.githubusercontent.com/assets/2809154/25923394/0041cb52-35e6-11e7-895a-e459b11a72d0.png)

And these are the dashboard routes, with 4 lazily loaded modules:
```
const DASHBOARD_ROUTES: Routes = [
    { path: '', component: DashboardComponent, children: [
        { path: '', component: HomeComponent },
        { path: 'queue/:hash', component: QueueComponent, canDeactivate: [ CanDeactivateGuard ] },
        { path: 'queue', component: QueueComponent },
        { path: 'channels', loadChildren: 'app/dashboard/channels/channels.module#ChannelsModule' },
        { path: 'videos', loadChildren: 'app/dashboard/videos/videos.module#VideosModule' },
        { path: 'stats', loadChildren: 'app/dashboard/stats/stats.module#StatsModule' },
        { path: 'albums', loadChildren: 'app/dashboard/albums/albums.module#AlbumsModule' }
    ], canActivate: [DashboardGuard] }
];
```

**Comment by mgechev** [comment]
This is what I see. Could be something Windows specific.
![screen shot 2017-05-10 at 15 33 34](https://cloud.githubusercontent.com/assets/455023/25924145/1226c570-3596-11e7-8fdf-4e83af46012f.png)

**Comment by mgechev** [comment]
Here's the source code of `DashboardRoutingModule` that I have:

```ts
import { NgModule } from '@angular/core';

import { Routes, RouterModule } from '@angular/router';

import { DashboardComponent } from './dashboard.component';
import { HomeComponent } from './home/home.component';
import { QueueComponent } from './queue/queue.component';

const DASHBOARD_ROUTES: Routes = [
    { path: '', component: DashboardComponent, children: [
        { path: '', component: HomeComponent },
        { path: 'queue/:hash', component: QueueComponent },
        { path: 'queue', component: QueueComponent },
        { path: 'videos', loadChildren: 'app/dashboard/videos/videos.module#VideosModule' },
        { path: 'albums', loadChildren: 'app/dashboard/albums/albums.module#AlbumsModule' }
    ]}
];

const dashboardRouting = RouterModule.forChild(DASHBOARD_ROUTES);

@NgModule({
    imports: [
        dashboardRouting
    ],
    exports: [ RouterModule ]
})
export class DashboardRoutingModule {}
```

**Comment by MrCroft** [comment]
Oh, yeah... That repo is a simplified version of what I have locally (2 less lazy modules).

It must be Windows specific then, because I've also just tested it on that repo and I get the same results, the lazy loaded modules don't show up.

**Comment by mgechev** [comment]
I don't have a windows vm unfortunately. I'm almost sure that the issue is somewhere [here](https://github.com/mgechev/ngrev/blob/master/src/background/states/module-tree.state.ts#L119-L187).

**Comment by MrCroft** [comment]
I can at least try and have a look at it tomorrow afternoon, after work, if I can't manage during. It's 2am here.
Although I haven't looked into Electron yet.

**Comment by mgechev** [comment]
It turns out I have license for Windows 10. I'll see what I can do too :-).

**Comment by mgechev** [comment]
@MrCroft try:

```
git clone https://github.com/mgechev/ngrev
cd ngrev && npm i
npm run build && npm start
```

Master should be fixed for windows now.

**Comment by MrCroft** [comment]
Thank you, Minko!
Just checked... It works perfectly ! :)
