### ISSUE TITLE
can't parse nx app

### ISSUE THREAD

**Issue by mhamri** [mgechev/ngrev#127]
![image](https://user-images.githubusercontent.com/8991783/110759152-433a7600-8288-11eb-97d0-bd9c234a13c0.png)

the aot is already enabled in our repo

![image](https://user-images.githubusercontent.com/8991783/110759290-682ee900-8288-11eb-9d54-9f7a3b42f39e.png)

it's nx project and I point to the tsconfig.app.json that is shown in the picture.

**Comment by mgechev** [comment]
Unfortunately, the project does not support nx. We'd love to get a contribution though. Closing for now, but if anyone wants to take the initiative and publish support, I'll be happy to review and merge.
