### ISSUE TITLE
Error Parsing CLI Project

### ISSUE THREAD

**Issue by darronj** [mgechev/ngrev#13]
I get the following when trying to open my angular-cli project. It builds with the --aot flag with no errors 

I'm using ngrev version 0.0.7

Error while parsing project
Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:
Cannot read property 'reference' of undefined

The same result is given when I use the tsconfig.json file in the root, or  /src/tsconfig.app.json

**Comment by mgechev** [comment]
Would you try the latest master (`git clone ... && cd ngrev && npm i && npm run build && npm start`)? I did fixes regarding primitive provider tokens yesterday.

If this doesn't help, I will be able to fix the issue if I can get a minimum demo which will allow me to reproduce it.

**Comment by mgechev** [comment]
Closing it due to lack of response. @darronj, please comment in case the problem still exists.

**Comment by darronj** [comment]
Sorry I didn't get back with you on this. I spent a weekend in bed. Evidently my problem was resolved, because it is fixed in the latest version. Thanks for all you do, I'm a huge fan.

**Comment by nicolasfourcade** [comment]
Hi! Bravo for your job. You made a nice tool to improve Angular apps. 
I try too use it on a open-source project mixing TypeScript and Saas files. It will be nice for me if I could have the view your ngrev propose. I post here my message because I got the same problem and I try to fix it by the same way but It fails for each attempt with the same message bellow. Maybe you can help me. Could you explain if it's possible where originally the problem is coming from when. Maybe it helps I join the tsconfig file
[tsconfig.json.txt](https://github.com/mgechev/ngrev/files/1097239/tsconfig.json.txt)

**Comment by nicolasfourcade** [comment]
I use expression "improve Angular apps" but I mean "understand angular app". It's much more realistic. Maybe later i will be able to improve ;-) but first retrieving a full description about the app using your tool will be great.

**Comment by mgechev** [comment]
I am happy the tool came handy!

**Comment by nicolasfourcade** [comment]
I'am trying to use it on an open source project grafana and I have always the same error message.

Error while parsing project
Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:
Cannot read property 'reference' of undefined

Do you think it is possible to override it ?

**Comment by mgechev** [comment]
Would you share source code so I can debug?

**Comment by nicolasfourcade** [comment]
I am working with an open source project my boss gave me : https://github.com/grafana/grafana. 
Backend in nodejs and front end in angularjs. You should find the tsconfig.json. Maybe too much file and some file not in angular but in typescript block your app. Do you think it's possible ?

**Comment by mgechev** [comment]
@nicolasfourcade this looks like an AngularJS (1.x) project, not Angular.

ngrev works only with Angular 2 and above, and AoT compilation compatible applications.

**Comment by nicolasfourcade** [comment]
That's why! My bad!It doesn't looks like obvious for me at that moment....

**Comment by rubigupta** [comment]
I am getting error when select tsconfig.add.json file using ngrev .Please give answer if anyone solved this.
