### ISSUE TITLE
[Feature request] Finding Circular Dependency.

### ISSUE THREAD

**Issue by gviligvili** [mgechev/ngrev#19]
Angular circular dependency is a nightmare, especially in big projects.
you can find yourself (or team mates) using @forwardRef, just because it seems right at the time.
 
This tool seems like a solid ground for targeting Circular dependency, any I could not find any other tools that solve it.  - so it would be great if you will add this feature :)

Thanks.

**Comment by mgechev** [comment]
This is mostly requirement for a tool for static code analysis. Maybe at some point I can provide integration with codelyzer.

Let's close the issue for now since it's not part of the roadmap.
