### ISSUE TITLE
Cant parse project when providing a service using a token and useFactory

### ISSUE THREAD

**Issue by bluEEil** [mgechev/ngrev#21]
I started working with ngrev today.
I think its a neat tool which is very important for the angular echo systems.
One issue that I found is that when I try to parse my project as is. I get an error about not allowing to use function. It always occured for all instance in my code where I tried to provide a token with useFactory, heres an example (I can't post the project that i'm working on specifically so ill only post examples):

`{ provide: 
            APP_INITIALIZER, 
            useFactory: (configService: ConfigService) => () => configService.load(), 
            deps: [ConfigService], multi: true 
        },`

so to overcome it, I just did something like this:
`
export function nothing(): any {}

...

{ provide: 
            APP_INITIALIZER, 
            useFactory: nothing, 
            deps: [ConfigService], multi: true 
        },`
which made the project parse, but ofc its not a great solution and also this configuration will not be visible in the ngrev output graph.

**Comment by mgechev** [comment]
Thanks for giving it a try!

The problem is in the arrow function, you cannot use them in provider declaration because the context is not statically inferable.

As I've mentioned in the readme, the project needs to be compatible with the AoT compilation of the framework.

**Comment by bluEEil** [comment]
If thats the case, could you give me some direction in how I should write such code to make it work without arrow functions? I tried doing something like moving the function into an exported function in the same file, but I still got the error. 
It doesn't make much sense if there is no simple way to provide with useFactory and use AoT in the same time right?

**Comment by mgechev** [comment]
You can use traditional function expression:

```
{
  provide: APP_INITIALIZER,
  useFactory: function (configService: ConfigService) {
    return function () {
      configService.load();
    }
  },
  deps: [ConfigService],
  multi: true
},
```

**Comment by bluEEil** [comment]
I see, ill give it a try, thanks :)
