### ISSUE TITLE
Angular 5 or CLI 1.5 not supported

### ISSUE THREAD

**Issue by chris-hq** [mgechev/ngrev#23]
command lines run:
ng new testingtester

( ... Project is created, dependancies downloaded .. )

cd testingtester
ng -v

```
Angular CLI: 1.5.0
Node: 8.7.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

Open ngrev.
Click on Select Project and select testingtester/src/tsconfig.app.json.

> Error while parsing project
> 
> Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:
> 
> Error encountered resolving symbol values statically. Expression form not supported (position 65:11 in the otiginal .ts file)

**Comment by MainaWycliffe** [comment]
Same issue here

**Comment by mgechev** [comment]
It's in master now. Pushing 0.0.13 today.

**Comment by rubigupta** [comment]
Yes I am getting same issue please give answer.

**Comment by santoshinmgr** [comment]
Hi,
May i use ngrev for angularJs project.
could any one help me on this.
