### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by Lindsor** [mgechev/ngrev#24]
Maybe you could provide some sort of indication that ngRev is working or loading the app.
I loaded my app and it stayed as a blank page for over half an hour. I ended up just killing it since im not sure if it failed or was just still loading the app (its quite large).

Thanks,

**Comment by mgechev** [comment]
@Lindsor this sounds like a good suggestion! There's loading indicator now as well but it's blocked because of some heavy computations happening in the UI thread.

I'd accept a PR for this feature!

**Comment by mgechev** [comment]
https://github.com/mgechev/ngrev/commit/822fcaefbcc450dbd61469819d5436da87e33392

But you'd need to use master.
