### ISSUE TITLE
Error while parsing project

### ISSUE THREAD

**Issue by subramn** [mgechev/ngrev#26]
I am getting the error - Error during parsing and make sure its compatible with Angular AOT Compiler

Function expressions are not supported in decorators. image attached

![image](https://user-images.githubusercontent.com/5430629/34316062-7c1c720a-e75b-11e7-8e5c-5c452cb6e649.png)

**Comment by mgechev** [comment]
@subramn can you compile your project with `ngc`?

**Comment by subramn** [comment]
[files.zip](https://github.com/mgechev/ngrev/files/1583810/files.zip)
i am not using the angular cli. i run the following npm command
"build": "webpack --config webpack.config.js",

attached the tsconfig.json ,package.json and webpack.config for your reference in zip file.

**Comment by mgechev** [comment]
I will take a look and let you know. Thank you so much for the files! :-)

**Comment by mgechev** [comment]
@subramn config looks good. Do you have a minimal demo I can use to reproduce the problem? Do you use the `userStateReducer` in your application compiled with `ngc`?

**Comment by mgechev** [comment]
Try 0.0.14.
