### ISSUE TITLE
Only apps based on Angular CLI supported?

### ISSUE THREAD

**Issue by mlc-mlapis** [mgechev/ngrev#27]
We have apps compiled by only `ngc` without any problems and then bundled using other tools like `SystemJS Builder`, `Rollup`, `CC`, ... and it looks that it is not possible to open such projects in `ngrev` ... selecting a correct `tsconfig.json` file ... the following error message appears:

![image](https://user-images.githubusercontent.com/5693835/34319298-7fe4ac76-e7de-11e7-9be9-a69d6dd96d91.png)

**Comment by mgechev** [comment]
It's not only Angular CLI apps, if they are compatible with ngc, everything should work.

Would you share minimal project so I can reproduce the issue?

**Comment by mlc-mlapis** [comment]
OK, I'll prepare a simple demo. Let me 2 hours ...

**Comment by mlc-mlapis** [comment]
Hi Minko, here is the demo project: https://github.com/mlc-mlapis/demo-angular-modal-gallery

It was used to solve some things with custom libs under AOT mode ... and now I just upgraded it to Angular 5.1.2 and RxJS 5.5.6. I also tested it again, if it runs JIT and AOT without problems. But now a bit different error message appeared when I tried to open the project in `ngrev` ... see below ... I also chose `tsconfig.aot.json` (AOT) or  `tsconfig.json` (JIT) but the error was still the same.

All necessary steps to run it are published in README.

![image](https://user-images.githubusercontent.com/5693835/34319618-3da8299c-e7e7-11e7-8f7d-54da6b1d3d1c.png)

**Comment by mgechev** [comment]
Oh, I see. Probably ngast uses your `tsconfig.json` file. Will experiment a bit later.

**Comment by mlc-mlapis** [comment]
@mgechev ... thanks for updated version 0.0.14, I tried it but the problem still pertains ... `Cannot find the root module of your project.`

**Comment by mgechev** [comment]
Very interesting...Do you have at least 1 module with at least 1 bootstrap component?

**Comment by mlc-mlapis** [comment]
... sure, you can see in the repository ... the main module is:
```
@NgModule({
	declarations: [
		AppComponent
	],
	imports: [
		BrowserModule,
		ReactiveFormsModule,
		SliderModule,
		ModalGalleryModule.forRoot()
	],
	providers: [],
	bootstrap: [AppComponent]
})
```

**Comment by mgechev** [comment]
@mlc-mlapis oh, sorry. Forgot about the link. Let me try to reproduce it :-).

**Comment by mgechev** [comment]
<img width="1068" alt="screen shot 2017-12-25 at 2 04 26 am" src="https://user-images.githubusercontent.com/455023/34329827-f63ebe68-e917-11e7-9e3b-c04e8ae1e983.png">

Use this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "lib": ["es2016", "dom"],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["../../node_modules/@types", "../../node_modules"],
    "types": ["node", "jasmine", "systemjs"]
  },
  "compileOnSave": false,
  "exclude": ["app/main-prod.ts"]
}
```

**Comment by mlc-mlapis** [comment]
@mgechev ... hmm, tried many combinations ... and there are my final observation:

1. If `tsconfig.json` contains property `"include": [...]` in `"compilerOptions"` with any content, then opening a project end with an error message:

![image](https://user-images.githubusercontent.com/5693835/34341516-26dc8e02-e999-11e7-8f2e-af02e7a6bb82.png)

2. If `tsconfig.json` contains property `"exclude": [...]` in `"compilerOptions"` with any content, then opening a project end with an error message (and doesn't contain property `"include": [...]`):

![image](https://user-images.githubusercontent.com/5693835/34341507-039c166a-e999-11e7-81c4-377a89f7a91a.png)

3. If `tsconfig.json` contains property `"outDir": "...",` in `"compilerOptions"` with any content, then opening a project end with an error message (and doesn't contain property`"exclude": [...]` ):

![image](https://user-images.githubusercontent.com/5693835/34341585-af1fa21c-e99a-11e7-80b2-ddb6d07ad153.png)

**The only workable actual setting of `tsconfig.json` is completely without parts `"include": [...]` and `"exclude": [...]` and `"outDir": "...",`.** I don't have any explanations for above combinations and it also seems that there are no reasons for such limitations .. when using of all 3 properties mentioned above is correct.

**Comment by mgechev** [comment]
Thanks for the observations! I can embed this in the tool. Until then, we can use this issue as reference.

Happy holidays! :-)
