### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by sonukapoor** [mgechev/ngrev#31]
I tried to run this in our angular cli project using 5.1.2 and received the following error:

> Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:

`{"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular",
"cancelFn":null,"runCount":0}}`

tsconfig.app.json:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts",
    .... bunch of our components that are excluded
    "jquery",
    "mcustomscrollbar"
  ]
}
```

I am able to compile the project fine with --aot.

**Comment by mgechev** [comment]
`ngrev` doesn't support `exclude`. What you can do is drop this config option and try again. For more details see https://github.com/mgechev/ngrev/issues/27.

**Comment by qtis** [comment]
dropping exclude did not help ;(

**Comment by LevapVeeskela** [comment]
I removed exclude, didn't help( Are you possible show to me sample work project or config?
