### ISSUE TITLE
Unable to parse the project

### ISSUE THREAD

**Issue by zlaja1983** [mgechev/ngrev#32]
![screen shot 2018-01-29 at 7 04 48 pm](https://user-images.githubusercontent.com/7635374/35541193-93063016-0527-11e8-8801-b566c407e0b4.png)

Here is my tsconfig.json

`{
	"extends": "./lib/ic/icTsConfig",
    "include": [
        "**/*.ts"
    ],
    "exclude": [
        "gen",
        "node_modules",
        "lib/dist",
        "lib/node-*",
        "**/*.spec.ts",
        "**/bootstrap_*.ts"
    ],
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": [
                "*",
                "lib/dist/*",
                "lib/dist/@types/*",
                "lib/node-coreweb/*",
                "lib/node-coreweb/@types/*"
            ]
        }
    }
}`

icTsConfig is

`{
	"extends": "../inin/ininTsConfig"
}`

and ininTSConfig is
`{
    "compilerOptions": {
        "module": "AMD",
        "moduleResolution": "Node",
        "noImplicitAny": true,
        "removeComments": false,
        "preserveConstEnums": true,
        "noEmit": true,
        "target": "ES5",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": ["es2017", "dom"],
        "strictNullChecks": true,
        "noStrictGenericChecks": true,
        "skipLibCheck": true
    }
}`

**Comment by zlaja1983** [comment]
Also the test-view-module looks like this

`import { AccountCodeService } from 'lib/ic/basl/@angularTestView/account-code.service';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { UpgradeModule } from '@angular/upgrade/static';
import { FormInputsModule } from 'lib/inin/basl/form-inputs/form-inputs.module';
import { TestViewComponent } from 'lib/ic/basl/@angularTestView/test-view.component';
import { DualListPickerModule } from 'lib/inin/basl/input/dualListPicker/dualListPicker.module';
import { FlexRowModule } from 'lib/inin/basl/layout/flex-row/flex-row.module';
import { ToggleModule } from 'lib/inin/basl/toggle/toggle.module';

import { PcorTooltipModule } from 'lib/inin/basl/tooltip/pcor-tooltip.module';
    // start of new modal testing
import { PcorModalModule } from 'lib/inin/basl/modal/pcor-modal.module';
import { PcorConfirmationModalModule } from 'lib/inin/basl/confirmationModal/pcor-confirmation-modal.module';
    // end of new modal testing

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormInputsModule,
    DualListPickerModule,
    FlexRowModule,
    ToggleModule,
    PcorTooltipModule,
    PcorModalModule,
    PcorConfirmationModalModule
],
  declarations: [
    TestViewComponent
  ],
  entryComponents: [
    TestViewComponent
  ],
  providers: [AccountCodeService]
})
export class TestViewModule {}
`

**Comment by mgechev** [comment]
You can look at https://github.com/mgechev/ngrev/issues/31 for more details. ngrev doesn't support `include` and `exclude`.
