### ISSUE TITLE
Load project failed for two different route paths that point to same lazy loaded module

### ISSUE THREAD

**Issue by MichalMaM** [mgechev/ngrev#33]
Load project failed for two different route paths that point to same lazy loaded module. Here is example with one route path that point to lazy loaded module https://github.com/MichalMaM/ngx-simple-project/blob/master/src/app/app.routing.ts (it works good), but for two different route paths ngrev throw error (routing source is here https://github.com/MichalMaM/ngx-simple-project/blob/widget/src/app/app.routing.ts):

> Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:
> 
> {"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}

I tried fork ngrev repo and add this commit https://github.com/MichalMaM/ngrev/commit/d68993f996d0b10ce5d0affe65943347aa4c79ad to my fork and then ngrev load my project correctly, but I'm not sure If this is good solution. For me it is hotfix that work :)

**Comment by mgechev** [comment]
@MichalMaM the fix totally makes sense. Would you open a PR with it? I have a minor style-related comment - would you capitalize the comments and add one space after `//`. Thanks!
