### ISSUE TITLE
Template compile error: Function expressions are not supported in decorators

### ISSUE THREAD

**Issue by IbeVanmeenen** [mgechev/ngrev#36]
Though my project is compatible with the Angular's AoT compiler, I get the following parse error:

<img width="532" alt="err" src="https://user-images.githubusercontent.com/673778/36616813-704b9eea-18e5-11e8-8b8e-13161002e14a.png">

Looks like the key error here is: `function expressions that are not supported in the decorators`, in the `app/app.module.ts` file, `line 45`, which has following code (line 45 is `useFactory`):

![code](https://user-images.githubusercontent.com/673778/36616920-d93304c0-18e5-11e8-8c7a-32479d46d251.png)

Any Ideas?
Oh, and thanks for providing such an amazing tool 😻

**Comment by mgechev** [comment]
Do not use arrow function but a regular anonymous functions.
