### ISSUE TITLE
Doesn't work with application generated by JHipster

### ISSUE THREAD

**Issue by gmarziou** [mgechev/ngrev#37]
Hello,

On Windows, there's an error which seems to be due to confusion between `/`and `\`:

This was run against this [project](https://github.com/jhipster/jhipster-sample-app) and works fine on Ubuntu.

![image](https://user-images.githubusercontent.com/361007/36629250-b5b30ad6-1953-11e8-8189-4f43d7ffbcd0.png)

**Comment by mgechev** [comment]
Would you share your `tsconfig.json` file?

**Comment by gmarziou** [comment]
Sure, for AOT: https://github.com/jhipster/jhipster-sample-app/blob/master/tsconfig-aot.json

**Comment by mgechev** [comment]
Perfect, thanks! Will try this when I find some spare time.

**Comment by mgechev** [comment]
JFYI, this app doesn't work on Mac either. It fails with an error during parsing of the project. Hopefully later this month or in March, I'll be able to take a look at this.

**Comment by gmarziou** [comment]
Thanks, there's no emergency. I am able to run on Ubuntu though it finds some issues with my tests and AOT, so maybe I should fix them or find a way to exclude tests from being parsed by ngrev.

**Comment by mgechev** [comment]
This will be very helpful!

**Comment by mgechev** [comment]
@gmarziou would you try now? Version 0.0.18 updates the compiler.

**Comment by gmarziou** [comment]
Thanks, I'll try tonight or tomorrow

**Comment by gmarziou** [comment]
It works fine.
I just had to delete tests which were not AOT-ready.
Thanks.

![image](https://user-images.githubusercontent.com/361007/38634598-49d41a00-3dc3-11e8-94b7-3aa9d6002811.png)

**Comment by mgechev** [comment]
❤️
