### ISSUE TITLE
angular v6 compatibilty?

### ISSUE THREAD

**Issue by sfabriece** [mgechev/ngrev#38]
Is this application compatible with angular v6?

**Comment by mgechev** [comment]
Do you get any errors trying to use it with Angular version 6?

**Comment by huskerona** [comment]
I am getting the same error on the Mac version of the tool as @sfabriece is getting on the Windows. However, the projects are not yet on NG v6, but rather 4 and 5.2 respectively. The same error appears.

**Error while parsing project**
> Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:
> {"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}

The projects are compatible with Angular AOT compiler as this is how it is being tested and deployed.

**Comment by bnymncoskuner** [comment]
I've tried this with my project as well. I can confirm that it does not work with v0.0.20 & v0.0.21. However, v0.0.19 works just fine.

**Comment by pinalbhatt** [comment]
I am seeing following  error when loading tsconig.app.json for Angular6  project with multiple apps.

![image](https://user-images.githubusercontent.com/6505848/40364807-2ebd08e6-5da1-11e8-91ad-c2d466a569a0.png)

**Comment by aaronte** [comment]
Same problem.

![image](https://user-images.githubusercontent.com/5732620/40375487-bf2d8a78-5db9-11e8-9965-76f657dd8729.png)

**Comment by iammelvin** [comment]
Any updates on this issue?

**Comment by admir86** [comment]
same problem...
dependencies:
```json
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@ngx-translate/core": "^10.0.2",
    "core-js": "^2.5.6",
    "rxjs": "^6.2.0",
    "zone.js": "^0.8.26"
  },

```
![image](https://user-images.githubusercontent.com/36576424/41231899-e7ec921c-6d84-11e8-8394-e74613bf52ca.png)

**Comment by momegas** [comment]
Same problem here on Ubuntu:
![screenshot from 2018-06-13 16-18-38](https://user-images.githubusercontent.com/21096981/41353646-818e1a02-6f25-11e8-9ece-861d4aeb6fd7.png)

**Comment by ruibasecone** [comment]
Somehow I get a:

```
Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:

[project-path]/src/app/app.module.ts(67,33): Error during template compile of 'AppModule'
  Could not resolve angulartics2/ga relative to [project-path]/src/app/app.module.ts..
```

OSx + angular 6 project (yes, with a angulartics2 as dependency)

**Comment by Xapuu** [comment]
Hello guys, I have the same problem, for now you can use 0.0.19 version (at least for my ng6 projects it works).

**Comment by mgechev** [comment]
Unfortunately, in the next a couple of weeks, I won't be able to look into these issues. Around mid-September, I should be able to align ngast to the latest changes in the Angular compiler.

It'll be very helpful if you can share sample projects where you can consistently reproduce the issues.

**Comment by jinbeomhong** [comment]
Basic application generated by CLI doesn't work too...

What about to make this application being used as a plugin of editor like vscode instead of as a stand-alone program?

**Comment by xRuhRohx** [comment]
Same issue here

**Comment by Hasan-git** [comment]
same here

**Comment by mgechev** [comment]
Try https://github.com/mgechev/ngrev/releases/tag/0.0.22
