### ISSUE TITLE
Doesn't work with ASP.NET Zero PhoneBookDemo app

### ISSUE THREAD

**Issue by timmackey** [mgechev/ngrev#39]
Cannot parse PhoneBookDemo project, which is compatible with AoT compiler.
![image](https://user-images.githubusercontent.com/16199122/38567558-6205ed70-3c9b-11e8-9a00-125c494924d3.png)

**Comment by mgechev** [comment]
Should be fixed in `0.0.18`.

**Comment by timmackey** [comment]
Thank you for fixing the parsing error.  However, I cannot see any of my components or methods.  Only modules.

**Comment by mgechev** [comment]
Is the project open source? If I have the source code, I can do some debugging to figure out where the issue comes from.

**Comment by timmackey** [comment]
@mgechev,

I attached the project files in two chunks, since this site won't accept large files.
If you want to fire up the entire project, you can find instructions here:
[https://aspnetzero.com/Documents/Getting-Started-Angular](url)

[angular.zip](https://github.com/mgechev/ngrev/files/1911290/angular.zip)

[aspnet-core.zip](https://github.com/mgechev/ngrev/files/1911291/aspnet-core.zip)

[README.zip](https://github.com/mgechev/ngrev/files/1911293/README.zip)
