### ISSUE TITLE
Distribution of the app

### ISSUE THREAD

**Issue by mgechev** [mgechev/ngrev#4]
Create binaries for:

- [x] macOS
- [ ] linux
- [ ] windows

**Comment by niklas-dahl** [comment]
also some usage information in the readme would be useful :)

**Comment by owenmecham** [comment]
A windows binary would be great for those of us tied to windows ;) The demo was awesome at ngconf.

**Comment by mgechev** [comment]
Would love to get a PR if anyone has time for this. I don't have windows atm.

**Comment by mgechev** [comment]
Just updated the readme with [further instructions](https://github.com/mgechev/ngrev).

**Comment by mgechev** [comment]
https://github.com/mgechev/ngrev/commits/master
