### ISSUE TITLE
Import failed with Angular 5

### ISSUE THREAD

**Issue by Aphax** [mgechev/ngrev#42]
Import isn't working on my angular 5 app, says it isn't AoT compatible, but my ng buid --prod command is working fine.
How can I make sure my app is AoT compatible ?
![nggrev error](https://user-images.githubusercontent.com/1375542/42319194-8a743330-8051-11e8-9a68-6f44a080b4d5.PNG)

**Comment by emulicus** [comment]
Yeah, same error here. Would like to try this tool as well.

**Comment by mgechev** [comment]
Unfortunately, in the next a couple of weeks, I won't be able to look into these issues. Around mid-September, I should be able to align ngast to the latest changes in the Angular compiler.

It'll be very helpful if you can share sample projects where you can consistently reproduce the issues.

**Comment by burkeallen** [comment]
I am getting similar results when trying to use against an angular 5 CLI project. AOT compiles successfully.

**Comment by mgechev** [comment]
Give a try to https://github.com/mgechev/ngrev/releases/tag/0.0.22.
