### ISSUE TITLE
Release 0.22 still cannot open the project

### ISSUE THREAD

**Issue by huskerona** [mgechev/ngrev#43]
Unlike the previous version, this time there are no error messages from zone. This is what I get:

> Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:
> {}

The project is compatible with AOT because that's the way it is compiled by both `ng server` and `ng build`

Best!

**Comment by mgechev** [comment]
Would you share a minimal demo so I can reproduce the problem?

Also, give a try to https://github.com/gothinkster/angular-realworld-example-app (after `npm i`) and let me know if it works with your setup.

Thanks for giving it a try!

**Comment by huskerona** [comment]
Same error. I even created a brand new project without any additional code.

**Comment by mgechev** [comment]
What's your OS?

**Comment by huskerona** [comment]
Good news. I downloaded your source code and ran `npm start`. The application opened with Chrome Dev Tools on the side. I loaded my work projects and it worked flawlessly. It opened the project in a second. When I tried to open with the application again (I guess that is the prod build) it failed to open it.

**Comment by huskerona** [comment]
> What's your OS?

macOS Mojave

**Comment by mgechev** [comment]
Perfect. I should be able to test on a machine.

**Comment by huskerona** [comment]
Minko, if you would be interested I just created a lot by running ngrev from terminal. There are no errors, but you might get the idea where the thing freezes.

Best!

**Comment by huskerona** [comment]
Minko, from the source code, running `npm run build:mac` created a new executable in `dist/mac`. Running the app from that location and then deploying to `/Applications/` made the application work like a charm. It is loading the project without any problems.

**Comment by jinbeomhong** [comment]
It doesn't work on macOS High Sierra 10.13.6. I created a new Angular project without editing any code and compile it using `ng build --aot`:

```
Error while parsing project

Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:

{}
```

**Comment by mgechev** [comment]
@jinbeomhong found the cause. In `/Users/USERNAME/Library/Application Support/ngrev` create `config.json` with content:

```
{
  "theme": "Light"
}
```

I'll push a fix in a minute.

**Comment by subramn** [comment]
Same error for me.

**Comment by mgechev** [comment]
@subramn would you try what I suggested above.

**Comment by subramn** [comment]
Thanks for the response. i am getting the following error
Error while parsing project

Cannot parse your project. Make sure it's compatible with the Angular's AoT compiler. Error during parsing:

{}

**Comment by mgechev** [comment]
@subramn what's your OS?

**Comment by subramn** [comment]
Windows 10

**Comment by mgechev** [comment]
Okay, the fix for you should be the same as the one I mentioned [above](https://github.com/mgechev/ngrev/issues/43#issuecomment-427517666) but instead of creating `config.json` in `/Users/USERNAME/Library/Application Support/ngrev` you should create it in the corresponding directory for Windows.

Should be inside `%APPDATA%`.

**Comment by mgechev** [comment]
Creating a new `*.exe`. I'll upload it in a few minutes.

**Comment by mgechev** [comment]
@subramn would you try again https://github.com/mgechev/ngrev/releases/tag/0.0.22.

**Comment by subramn** [comment]
Thank you so much. i tried and it works now.

**Comment by mgechev** [comment]
@xperiments would you create a separate issue if you have a chance to share a minimum demo?
