### ISSUE TITLE
doesn't work well with large projects

### ISSUE THREAD

**Issue by oocx** [mgechev/ngrev#46]
The idea for your tool is great, but it does not work well with large projects. The output is just a huge unreadable ball of lines and boxes (makes our architecture look much worse than it actually is :) ).

We have 159 modules, 351 components, 283 services, 210 data model files, and 28 pipes. For such a large application, we could really use a tool that helps us analyse the application structure. Unfortunately, the current layout generated by ngrev does not help us.

Thanks,
Mathias

**Comment by mgechev** [comment]
Thanks for giving it a try!

Vis.js allows a custom layout. If you're interested in contributing, I'd love to merge a PR with an improvement. For an inspiration, you can look at Graphviz.

**Comment by mgechev** [comment]
Just did [this](https://github.com/mgechev/ngrev/commit/872a31633a435007937771ec7e029831222138b4) minor improvement in "Application View". I hope it works better.

In case you have ideas for further improvement, feel free to introduce a more appropriate layout or share ideas on how we can make it better.

**Comment by oocx** [comment]
Great, thanks for the quick response! I'll try your changes next week when I'm back at work.
