### ISSUE TITLE
VSCode extension version

### ISSUE THREAD

**Issue by bampakoa** [mgechev/ngrev#51]
Hi,

Thanks very much for this awesome tool! Are there any plans to release it as a VSCode extension also? It should be really handy, especially for newcomers in a project, to take a quick look at the structure while navigating the code.

Thanks!

**Comment by mgechev** [comment]
It'd not have the bandwidth for that. I'd love to reference an extension if anyone is planning to implement it.

**Comment by bampakoa** [comment]
> It'd not have the bandwidth for that

@mgechev Could you please clarify what do you mean?

**Comment by mgechev** [comment]
I would not have the time to implement a VSCode plugin for ngrev, but I agree this is a fantastic feature that you suggested.

If you think you'd be able to introduce VSCode plugin in this repo, I'd love to reopen the issue so we can track the progress. Also, if restructuring of the source code will simplify the implementation of a VSCode in a separate repo, let me know. We can track this in another issue.

**Comment by bampakoa** [comment]
@mgechev thanks for the clarification. Yes, I would definitely be interested on this to help. I think that it would benefit the Angular community :smiley:

**Comment by bampakoa** [comment]
@mgechev if you could re-open issue to fire up the discussion, that would be great. Thanks!

**Comment by bampakoa** [comment]
@mgechev we could be inspired by [Angular Console](https://github.com/nrwl/angular-console) repo about the structure. It currently uses [Nx](https://nx.dev/) but I think we could equally incorporate Angular CLI for this.

**Comment by bampakoa** [comment]
hey @mgechev . Just to let you know that I am currently working to submit an initial version of a PR for this.

**Comment by bampakoa** [comment]
@mgechev I was thinking to use **Nx** for structuring the repo, as in Angular Console, but I have some second thoughts. Let's use Angular CLI projects feature and keep it simple for now.

**Comment by bampakoa** [comment]
@mgechev the application imports Electron artifacts directly from the `electron` package which makes it tightly coupled with the Electron renderer. We could do one of the following to decouple it:

1. Supply a custom provider with `Inject` for every artifact that we import, such as `ipcRenderer` and `remote`, as described [here ](https://angular.io/guide/dependency-injection-in-action#supply-a-custom-provider-with-inject).
2. Use a 3rd party library such as [ngx-electron](https://github.com/ThorstenHans/ngx-electron) and replace it with an all-in-one custom provider.

What do you think?

**Comment by mgechev** [comment]
Closing for now. If there's progress in the future, please open a PR or another issue.
