### ISSUE TITLE
Is there a programatic API I could use to get the dependencies of a component?

### ISSUE THREAD

**Issue by davidfirst** [mgechev/ngrev#55]
I'm trying to extract all dependencies of a component (similar to [node-dependency-tree](https://github.com/dependents/node-dependency-tree)), which seems to be a non-trivial task with Angular. 
This project seems the closest I can get, however, I need it for a CLI tool.

If there is no such an API, can you point me to the main point where the UI gets the files? I guess I'll be able to take it from there and post a PR. (hopefully, the UI is not coupled to the logic).

Thanks!

**Comment by mgechev** [comment]
You can do this with this tool. See ngrev.

**Comment by davidfirst** [comment]
I'm confused. 
"ngrev" is this library, according to the description it's "Graphical tool for reverse engineering of Angular projects".
I need the same but without the graphical interface. Just CLI or some API. 
How can I achieve this?

Thanks.

**Comment by mgechev** [comment]
You can use ngast to build something like ngrev without graphical interface. I mentioned ngrev since you can use it as an example :)
