### ISSUE TITLE
Cannot open ngrev on osx mojave 10.14.5

### ISSUE THREAD

**Issue by gpsimmo** [mgechev/ngrev#56]
after updating to `ngrev-0.0.27.dmg` the app will not open on osx mojave v10.14.5

> ngrev cannot be opened because of a problem.
> Check with the developer to make sure ngrev works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS

**Comment by mgechev** [comment]
Cannot reproduce it on the same macOS version.

**Comment by mgechev** [comment]
Just reuploaded the assets. Would you try again?

**Comment by gpsimmo** [comment]
Hey Minko, 
i uninstalled and re-installed with new assets. All is working ok now.
many thanks.... awesome work
