### ISSUE TITLE
Error parsing with lazy loading modules

### ISSUE THREAD

**Issue by xuxicheta** [mgechev/ngrev#58]
I have routes likes this
```
export const appRoutes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'authorize' },
  { path: 'authorize', component: AuthorizationComponent },
  {
    path: 'admin',
    loadChildren: () => import('./@admin/admin.module').then(m => m.AdminModule),
  }
```
where `@admin` is folder name

And it is cause error 

> Function expression are not supported in decorators

**Comment by mgechev** [comment]
This, unfortunately, is not supported by the Angular compiler. The Angular CLI rewrites these dynamic imports to string-based `loadChildren` syntax.

I understand it's a bad issue, but there's no way to fix it unless I fork the compiler.
