### ISSUE TITLE
Unexpected value 'null' declared by the module .... in ..  at syntax error

### ISSUE THREAD

**Issue by tomasro27** [mgechev/ngrev#7]
A javascript error ocurred inthe main process
Unexpected value 'null' declared by the module .... in ..  at syntax error

When trying to open a project folder

**Comment by mgechev** [comment]
Would you share the entire stack trace?

**Comment by tomasro27** [comment]
https://cloud.githubusercontent.com/assets/4178358/24022677/2e7c7a5a-0a65-11e7-98a0-a9e8115b0104.PNG

**Comment by mgechev** [comment]
Can you compile your application using the Angular AoT compiler? If it's not compatible with it then ngrev won't be able to parse it.

**Comment by tomasro27** [comment]
This might be why then. I will try later, but you can close the issue for now.  It might be a good idea to put this on the readme, so that others know they need aot for the tool to work.
thanks!

**Comment by tomasro27** [comment]
It did work with a smaller project btw

**Comment by mgechev** [comment]
I updated the project (version 0.0.1) with a better error message which explains this. You can try the latest version which has 3 small features included.

**Comment by tomasro27** [comment]
Sounds good, thanks!
Side question:
Do you need to specify the root of the angular project for it to work, or can you select any subfolder?

**Comment by mgechev** [comment]
You should select a `tsconfig.json` which points to the root module. It may work with lazy-loaded module as well but it hasn't been tested.
